version: "3.8"

services:
  app:
    depends_on:
      mysqldb:
       condition: service_healthy
    build: .
    restart: on-failure
    env_file: ./.env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'

  mysqldb:
    image: mysql:8.0.32
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_PASSWORD
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    command: --explicit_defaults_for_timestamp=1
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: "mysql -u$MYSQLDB_USER -p$MYSQLDB_PASSWORD $MYSQLDB_DATABASE -e 'select 1'"
      interval: 30s
      retries: 5
      timeout: 30s
      start_period: 5s

volumes:
  db:
