spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web_store
    username: your_username
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#  profiles:
#    active: googlecloud

logging:
  file:
    path: var/logs/app/
    name: application.log

  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS XXX} %-5level [%t] %logger{36} - %msg%n"

  logback:
    rollingpolicy:
      file-name-pattern: application-log.%d{yyyy-MM-dd}.%i.gz.log
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 1GB

  level:
    com.example.portfolio.webstorespring: info

# Environment Variables
sender:
  email: ${SENDER_EMAIL:your@email.com}
  password: ${SENDER_PASSWORD:password}

cors:
  allowed-origin-patterns: ${CORS_ALLOWED_ORIGIN_PATTERNS:http://localhost:4200}

confirmation:
  link:
    email: ${CONFIRMATION_LINK_EMAIL:http://localhost:4200/registration/confirm?token=}
    reset-password: ${CONFIRMATION_LINK_RESET_PASSWORD:http://localhost:4200/reset-password/confirm?token=}
    backup-email: ${BACKUP_EMAIL_LINK:http://localhost:4200/backup-email/confirm?token=}

shipment:
  address: ${SHIPMENT_ADDRESS:your_shipment_address}

account:
  image:
    url: ${ACCOUNT_IMAGE_URL:https://i.imgur.com/a23SANX.png}

jwt:
  secret-key: ${JWT_SECRET_KEY:5970337336763979244226452948404D6351665468576D5A7134743777217A25}

admin:
  email: ${ADMIN_EMAIL:admin@admin.com}
  password: ${ADMIN_PASSWORD:Password123!}
